name: Generate and Update Terraform Docs
on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  generate-docs:
    name: Generate Terraform Docs
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install jq (JSON Parser)
        run: |
          sudo apt-get install -y jq

      - name: Fetch and Install Latest Version of Terraform Docs
        run: |
          echo "Fetching the latest version of terraform-docs"
          version=$(curl -s https://api.github.com/repos/terraform-docs/terraform-docs/releases/latest | jq -r '.tag_name' | sed 's/v//')
          echo "Latest version of terraform-docs: $version"
          download_url="https://github.com/terraform-docs/terraform-docs/releases/download/v${version}/terraform-docs-v${version}-linux-amd64.tar.gz"
          echo "Download URL: $download_url"
          curl -Lo ./terraform-docs.tar.gz "$download_url"
          tar -xzf terraform-docs.tar.gz
          chmod +x terraform-docs
          sudo mv terraform-docs /usr/local/bin/terraform-docs

      - name: Update terraform-docs.yml with the latest version
        run: |
          echo "Updating .terraform-docs.yml to use version $version"
          sed -i "s/version:.*/version: \"$version\"/" .terraform-docs.yml
          cat .terraform-docs.yml

      - name: Generate Terraform Docs and Update README
        run: |
          /usr/local/bin/terraform-docs -c .terraform-docs.yml .

      - name: Commit and Push Changes
        run: |
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"
          git add .
          git commit -m "Update Terraform Docs" || echo "No changes to commit"

      - name: Push Changes to GitHub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push origin HEAD:${{ github.head_ref }} -f
